### ISSUE TITLE
$wizard.config is not a function

### ISSUE THREAD

**Issue by redaz808** [shaunxu/angular-toolkits#1]
Its not working, followed your instructions but getting an error: $wizard.config is not a function.
Even your plunkr demo has the same error.

**Comment by shaunxu** [comment]
Sorry about this. I updated the source code and renamed <code>config()</code> to <code>$new()</code> due to a bugfix. But I didn't updated plunker demo. Please use <code>$wizard.$new()</code>, the parameter structure is the same.

I had change the code in plunker please try again.

Please let me know if any future questions.

**Comment by redaz808** [comment]
I noticed this while looking at your factory class. Many thanks for the
prompt response!
